name: 'Auto Promotion'
description: 'Apply environment promotion rules from config'
inputs:
  user:
    description: 'The User to use for accessing target repositories'
    required: true
  email:
    description: 'Email to use in signature'
    required: true
  password:
    description: 'Password or access token for authenticating with target repositories'
    required: false
  config:
    description: 'Path to config file'
    required: true
  trigger:
    description: 'Release trigger that can be used for filtering targets'
    required: true
  variables:
    description: 'Space separate list of variable / value pairs in the format of x=y'
    required: true
runs:
  using: 'docker'
  image: 'docker://shuttlerock/auto-promote-action:1.13'
  args:
    - 'auto-promote'
    - '--git-user'
    - ${{ inputs.user }}
    - '--git-email'
    - ${{ inputs.email }}
    - '--git-password'
    - ${{ inputs.password }}
    - '--config'
    - ${{ inputs.config }}
    - '--trigger'
    - ${{ inputs.trigger }}
    - '--variables'
    - ${{ inputs.variables }}
